# Generated by Django 4.2.4 on 2023-09-01 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mycourse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('prn', models.CharField(max_length=100, primary_key='True', serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('dob', models.DateField(default='1998-01-01')),
                ('dept_ID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mycourse.dept')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_ID', models.CharField(max_length=100, primary_key='True', serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('dept_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycourse.dept')),
            ],
        ),
    ]
